### ISSUE TITLE
Cover all Tx submission errors in monads for greater DX

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/cem-script#65]
Now bunch of Cardano errors are returned in raw form, which is hard to comprehend for user. We need to cover all such errors, preferably by static check of constraints DSL.

**TODO:**

- [ ] Handle `TxInOutdated` and `WrongSlot` events
- [ ] Static validation: all spec maps are total
- [ ] Static validation: signers, coins-selection and minting are correct
- [ ] Graceful errors on coin selection

Blocked by #24
