### ISSUE TITLE
Better checks and error messages on L1 connection 

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/cem-script#71]
**TODO:**

- [ ] Catch `Network.Socket.connect` errors: no rights or socket not existing
- [ ] Check slot number is not stall and overall correct
- [ ] Check Plutus and Era match
