### ISSUE TITLE
Add project code coverage

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/cem-script#83]
**TODO:**

- [ ] Compile and commit HPC report
- [ ] Share it on Github Pages
- [ ] Add it to CI
